### ISSUE TITLE
Compilation error on build to ios device (arm64)

### ISSUE THREAD

**Issue by Limonlol** [icerockdev/moko-maps#2]
moko-maps-google is not going on a device with an error `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld invocation reported errors`

**Comment by Alex009** [comment]
error is: 
`ld: framework not found GoogleMapsBase`

**Comment by Alex009** [comment]
fixed in #1
