### ISSUE TITLE
Can't use maps-mapbox 

### ISSUE THREAD

**Issue by zalewskise** [icerockdev/moko-maps#45]
I tried to update moko-maps to `0.5.0` and got the error while building:

>    Could not find com.mapbox.navigator:mapbox-navigation-native:7.0.0.
>      Searched in the following locations:
>        - https://jcenter.bintray.com/com/mapbox/navigator/mapbox-navigation-native/7.0.0/mapbox-navigation-native-7.0.0.pom
>        - https://dl.google.com/dl/android/maven2/com/mapbox/navigator/mapbox-navigation-native/7.0.0/mapbox-navigation-native-7.0.0.pom
>        - https://dl.bintray.com/ekito/koin/com/mapbox/navigator/mapbox-navigation-native/7.0.0/mapbox-navigation-native-7.0.0.pom
>        - https://dl.bintray.com/icerockdev/moko/com/mapbox/navigator/mapbox-navigation-native/7.0.0/mapbox-navigation-native-7.0.0.pom
>        - https://kotlin.bintray.com/native-xcode/com/mapbox/navigator/mapbox-navigation-native/7.0.0/mapbox-navigation-native-7.0.0.pom
>      Required by:
>          project :common > dev.icerock.moko:maps-mapbox:0.5.0 > dev.icerock.moko:maps-mapbox-android:0.5.0 > com.mapbox.mapboxsdk:mapbox-android-navigation:0.42.6

As for dependencies I'm using:
    "dev.icerock.moko:maps:0.5.0"
    "dev.icerock.moko:maps-mapbox:0.5.0"

Both set in common source set.

**Comment by Alex009** [comment]
@zalewskise hi!
please add repository `maven { url = uri("https://mapbox.bintray.com/mapbox") }`

**Comment by zalewskise** [comment]
@Alex009 
Oh right! I didn't have that one 💦 It was working fine on `0.4.0-dev-4` though, maybe it's good to update the readme file about it 😄 
Thank you! 🙏

**Comment by Alex009** [comment]
i already update readme, thx.
just in this update mapbox on android got support of `buildRoute`
